import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DarkModeToggle from './pages/DarkMode';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
          <link rel="icon" href="./assets/img/favicon.png"/>
          {/* Se você estiver usando um formato ou nome diferente, ajuste o caminho */}
        </head>
      <body className="{inter.className} bg-white dark:bg-black text-black dark:text-white">
      <header className="p-4 flex justify-between items-center">
          <h1 className="text-xl">Telos</h1>
          <DarkModeToggle />
        </header>
        {children}
      </body>
    </html>
  );
}
